### ISSUE TITLE
Background colour preferences are only applied for the scrollbar

### ISSUE THREAD

**Issue by maxigaz** [wustho/baca#14]
I'm using baca installed via `pipx` on postmarketOS. Setting the background colour values in `~/.config/baca/config.ini` has no effect.

```
[Color Dark]
Background = #002B36
Foreground = #f5f5f5
Accent = #0178d4

[Color Light]
Background = #FDF6E3
Foreground = #1e1e1e
Accent = #0178d4
```

I have the above in my configuration, and yet the original colour is used.

Other settings work though (e.g. changing the value of `TextJustification` or `ShowImageAsANSI`).

**Comment by maxigaz** [comment]
I've just noticed that setting the background colour does have an effect, but not on the background of the book's content. It only changes the background of the scrollbar on the right. (To test it, try setting `Background` to `red`. It should stand out immediately.)

I can also reproduce this on the main branch, running on Arch Linux.

**Comment by maxigaz** [comment]
I've taken a look at `style.css`. The quick and dirty solution would be to force every element to have the specified background [here](https://github.com/wustho/baca/blob/main/src/baca/resources/style.css#L12), like so:

```scss
.-dark-mode * {
  background: $dark-bg;
  scrollbar-color: $dark-accent;
  scrollbar-background: $dark-bg;
}

.-light-mode * {
  background: $light-bg;
  scrollbar-color: $light-accent;
  scrollbar-background: $light-bg;
}
```

The downside of this is that it also changes the background of chapter titles and other headings in pretty mode. (When pretty mode is disabled, everything looks fine based on my brief testing.)

The cleanest solution would be to use selectors only for the elements that are currently not affected by the colour settings such as the text content area, but I haven't been able to find anything that works yet.
